### ISSUE TITLE
mkdoc build failed 

### ISSUE THREAD

**Issue by thinkycx** [ctf-wiki/ctf-wiki#359]
**Enviroment**
- ubuntu 16.04
- Python 2.7.12

**I used the method in readme.md**

```# 1. clone
git clone git@github.com:ctf-wiki/ctf-wiki.git
# 2. requirements
pip install -r requirements.txt
# generate static file in site/
mkdocs build
# deploy at http://127.0.0.1:8000
mkdocs serve
```

when run **mkdocs build** in bash, the output is : 

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /root/Servers/ctf-wiki/site
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 260, in build
    files = get_files(config)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/structure/files.py", line 221, in get_files
    for source_dir, dirnames, filenames in os.walk(config['docs_dir'], followlinks=True):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
```

after add `reload(sys);sys.setdefaultencoding('utf-8')` into mkdocs.
**cat /usr/local/bin/mkdocs**

```
#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from mkdocs.__main__ import cli

reload(sys)
sys.setdefaultencoding('utf-8')

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

run again: **mkdocs build**

```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /root/Servers/ctf-wiki/site
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 14, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/commands/build.py", line 260, in build
    files = get_files(config)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/structure/files.py", line 221, in get_files
    for source_dir, dirnames, filenames in os.walk(config['docs_dir'], followlinks=True):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 54-63: ordinal not in range(128)
```

**Comment by Ir1d** [comment]
需要 python3

**Comment by thinkycx** [comment]
@Ir1d 
Thanks. I have built it successfully. There are some warnings.Do you know why?
```
➜  ctf-wiki git:(master) mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /root/Servers/ctf-wiki/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - android/readme.md
  - android/basic_reverse/dynamic/ida_smali_debug.md
  - crypto/streamcipher/prng/problem.md
  - misc/others.md
  - pwn/heap/leak_heap.md
  - pwn/heap/ptmalloc_check.md
  - pwn/mitigation/Canary.md
  - reverse/anti-debug/thread_local_storage.md
WARNING -  Documentation file 'executable/elf/program_loading.md' contains a link to 'executable/ELF/figure/shared_object_segments_addresses.png' which is not found in the documentation files.
WARNING -  Documentation file 'pwn/mitigation/Canary.md' contains a link to 'pwn/mitigation/media/15107152089668/15107154540302.jpg' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/checkremotedebuggerpresent.md' contains a link to 'reverse/anti-debug/ntqueryinformationprocess/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/isdebuggerpresent/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/ntglobalflag/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/checkremotedebuggerpresent/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/unpack/unpack-dll.md' contains a link to 'reverse/unpack/manually-fix-iat/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/unpack/unpack-dll.md' contains a link to 'reverse/unpack/manually-fix-iat/index.html' which is not found in the documentation files.
➜  ctf-wiki git:(master) mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - android/readme.md
  - android/basic_reverse/dynamic/ida_smali_debug.md
  - crypto/streamcipher/prng/problem.md
  - misc/others.md
  - pwn/heap/leak_heap.md
  - pwn/heap/ptmalloc_check.md
  - pwn/mitigation/Canary.md
  - reverse/anti-debug/thread_local_storage.md
WARNING -  Documentation file 'executable/elf/program_loading.md' contains a link to 'executable/ELF/figure/shared_object_segments_addresses.png' which is not found in the documentation files.
WARNING -  Documentation file 'pwn/mitigation/Canary.md' contains a link to 'pwn/mitigation/media/15107152089668/15107154540302.jpg' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/checkremotedebuggerpresent.md' contains a link to 'reverse/anti-debug/ntqueryinformationprocess/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/isdebuggerpresent/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/ntglobalflag/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/anti-debug/example.md' contains a link to 'reverse/anti-debug/checkremotedebuggerpresent/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/unpack/unpack-dll.md' contains a link to 'reverse/unpack/manually-fix-iat/index.html' which is not found in the documentation files.
WARNING -  Documentation file 'reverse/unpack/unpack-dll.md' contains a link to 'reverse/unpack/manually-fix-iat/index.html' which is not found in the documentation files.
[I 180901 05:04:32 server:292] Serving on http://127.0.0.1:8000
[I 180901 05:04:32 handlers:59] Start watching changes
[I 180901 05:04:32 handlers:61] Start detecting changes
^C[I 180901 05:08:38 server:313] Shutting down...
```

**Comment by iromise** [comment]
These files are not in the mkdocs.yml.

**Comment by thinkycx** [comment]
@iromise  Thanks.
