### ISSUE TITLE
本地mkdocs报错

### ISSUE THREAD

**Issue by littleheary** [ctf-wiki/ctf-wiki#618]
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/build.py", line 117, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/build.py", line 96, in _build_template
    output = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/ctf/ctf-wiki/mkdocs-material/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/ctf/ctf-wiki/mkdocs-material/material/base.html", line 184, in top-level template code
    {% block disqus %}
  File "/ctf/ctf-wiki/mkdocs-material/material/base.html", line 185, in block "disqus"
    {% include "partials/integrations/disqus.html" %}
  File "/ctf/ctf-wiki/mkdocs-material/material/partials/integrations/disqus.html", line 12, in top-level template code
    <h2 id="__comments">{{ lang.t("meta.comments") }}</h2>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'lang' is undefined

**Comment by AngelKitty** [comment]
@littleheary python版本问题？要么你先试试升级到python3.6

**Comment by yechs** [comment]
我也遇到了相类似的问题……不过最后报的错误不一样就是了


环境是 Python 3.8.2 (ArchLinux)
从 requirements.txt 中安装的 dependencies 版本是：
```
Jinja2-2.11.2 Markdown-3.2.1 MarkupSafe-1.1.1 PyYAML-5.3.1 Pygments-2.6.1 click-7.1.1 future-0.18.2 joblib-0.14.1 livereload-2.6.1 lunr-0.5.6 mkdocs-1.1 mkdocs-material-5.1.0 mkdocs-material-extensions-1.0b1 nltk-3.5 pymdown-extensions-7.0 regex-2020.4.4 tornado-6.0.4 tqdm-4.45.0
```


在运行 `mkdocs build` 之后报错：

<details>
<summary>Traceback (most recent call last):</summary>

```
  File "/home/[redacted]/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/[redacted]/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/[redacted]/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 288, in build
    _build_theme_template(template, env, files, config, nav)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 114, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 93, in _build_template
    output = template.render(context)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/[redacted]/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/[redacted]/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/[redacted]/.local/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/home/[redacted]/.local/lib/python3.8/site-packages/material/base.html", line 108, in top-level template code
    {% block header %}
  File "/home/[redacted]/.local/lib/python3.8/site-packages/material/base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "/home/[redacted]/.local/lib/python3.8/site-packages/material/partials/header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "/home/[redacted]/.local/lib/python3.8/site-packages/material/partials/logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/utils/filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 223, in normalize_url
    path = path_to_url(path or '.')
  File "/home/[redacted]/.local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
```

</details>

`AttributeError: 'dict' object has no attribute 'split'`

**Comment by yechs** [comment]
https://github.com/mkdocs/mkdocs/issues/2052

似乎是 Material theme 的问题……
