### ISSUE TITLE
mkdocs build 问题

### ISSUE THREAD

**Issue by Autumn-27** [ctf-wiki/ctf-wiki#682]
您好，我使用mkdocs build时出现这个问题
Traceback (most recent call last):
  File "f:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Python\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "f:\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "f:\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "f:\python\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "f:\python\lib\site-packages\mkdocs\__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "f:\python\lib\site-packages\mkdocs\commands\build.py", line 285, in build
    _build_theme_template(template, env, files, config, nav)
  File "f:\python\lib\site-packages\mkdocs\commands\build.py", line 108, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "f:\python\lib\site-packages\mkdocs\commands\build.py", line 87, in _build_template
    output = template.render(context)
  File "f:\python\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "f:\python\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "f:\python\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "f:\python\lib\site-packages\material\404.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "f:\python\lib\site-packages\material\base.html", line 108, in top-level template code
    {% block header %}
  File "f:\python\lib\site-packages\material\base.html", line 109, in block "header"
    {% include "partials/header.html" %}
  File "f:\python\lib\site-packages\material\partials\header.html", line 7, in top-level template code
    {% include "partials/logo.html" %}
  File "f:\python\lib\site-packages\material\partials\logo.html", line 5, in top-level template code
    <img src="{{ config.theme.logo | url }}" alt="logo">
  File "f:\python\lib\site-packages\mkdocs\utils\filters.py", line 14, in url_filter
    return normalize_url(value, page=context['page'], base=context['base_url'])
  File "f:\python\lib\site-packages\mkdocs\utils\__init__.py", line 262, in normalize_url
    path = path_to_url(path or '.')
  File "f:\python\lib\site-packages\mkdocs\utils\__init__.py", line 290, in path_to_url
    return '/'.join(path.split('\\'))
AttributeError: 'dict' object has no attribute 'split'

**Comment by iromise** [comment]
可以说一下详细的环境么？以及这个问题可以去参考下 mkdocs 的使用方式，这个问题应该不是由于这个项目里的文件导致的。
