### ISSUE TITLE
mkdocs 本地部署问题

### ISSUE THREAD

**Issue by iselt** [ctf-wiki/ctf-wiki#841]
您好，我在mkdocs build的时候遇到问题
[root@VM-0-5-centos ctf-wiki]# python3 scripts/docs.py build-all
Updating en
Updating zh
Building docs for: zh
Error reading page 'android/basic_operating_mechanism/native_layer/so.md': format() argument must be a formatter instance, not a class
Traceback (most recent call last):

  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)

  File "/usr/local/lib64/python3.6/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)

  File "/usr/local/lib64/python3.6/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)

TypeError: wrap() missing 1 required positional argument: 'outfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "scripts/docs.py", line 458, in <module>

  File "scripts/docs.py", line 279, in build_all

  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)

  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)

  File "/usr/local/lib/python3.6/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)

  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)

  File "/usr/local/lib/python3.6/site-packages/pymdownx/superfences.py", line 863, in run
    return self.search_nested(lines)

  File "/usr/local/lib/python3.6/site-packages/pymdownx/superfences.py", line 697, in search_nested
    self.eval_quoted(ws, content, quote_level, start, end)

  File "/usr/local/lib/python3.6/site-packages/pymdownx/superfences.py", line 450, in eval_quoted
    self.process_nested_block(ws, content, start, end)

  File "/usr/local/lib/python3.6/site-packages/pymdownx/superfences.py", line 471, in process_nested_block
    attrs=self.attrs if self.attr_list else {}

  File "/usr/local/lib/python3.6/site-packages/pymdownx/superfences.py", line 794, in highlight
    code_block_count=self.highlight_ext.pygments_code_block

  File "/usr/local/lib/python3.6/site-packages/pymdownx/highlight.py", line 381, in highlight
    code = highlight(src, lexer, formatter)

  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)

  File "/usr/local/lib64/python3.6/site-packages/pygments/__init__.py", line 69, in format
    raise TypeError('format() argument must be a formatter instance, '

TypeError: format() argument must be a formatter instance, not a class

**Comment by boom-1232** [comment]
+1

**Comment by arttnba3** [comment]
Hi iselt,

Thanks for reaching out CTF-wiki team. Could you please provide more detailed information for us to test this problem? For example:

- Your OS version
- Your python version
- ......

By the way besides above, could you please try to update your OS environment to the latest version to check whether the problem could be fixeed? We've check the building flow of CTF-wiki on latest Python environment and it does work for us. So if you're in need of building and deploying the CTF-wiki on your host quickly, setting up a new environment(or using the Docker) might be helpful for you.

If you have any further concerns, or if you have any other thoughts, please feel free to contact us.

Best regards,
arttnba3
CTF-wiki team
30/09/2024
